from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

class CartItemAdd(BaseModel):
    menu_item_id: int
    quantity: int = Field(ge=1, default=1)

class CartItemResponse(BaseModel):
    menu_item_id: int
    name: str
    unit_price: float
    quantity: int
    total_price: float

class CartResponse(BaseModel):
    show_id: int
    items: List[CartItemResponse]
    subtotal: float

class CheckoutLineItem(BaseModel):
    menu_item_id: int
    quantity: int = Field(ge=1, default=1)

class CheckoutRequest(BaseModel):
    show_id: int
    screen_id: int
    seat: str
    idempotency_key: str = Field(..., min_length=8, description="Unique transaction key generated by client")
    items: List[CheckoutLineItem] = Field(..., min_length=1, description="Items to purchase")
    offer_code: Optional[str] = None

class CheckoutResponse(BaseModel):
    order_id: int
    status: str
    seat: str
    subtotal: float
    discount: float
    total: float
    idempotency_key: str
    items: List[CartItemResponse]
    created_at: datetime
